# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20170930_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='row_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='row_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
