# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0029_auto_20170929_2044'),
        ('transactions', '0005_auto_20171002_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRun',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(default='new', max_length=20)),
                ('extract_date', models.DateTimeField(blank=True, editable=False)),
                ('extract_run_id', models.IntegerField()),
                ('has_header_row', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budget.BankAccount')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical run',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='new', max_length=20)),
                ('extract_date', models.DateTimeField(auto_now_add=True)),
                ('extract_run_id', models.IntegerField()),
                ('has_header_row', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.BankAccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicaltransaction',
            name='extract_date',
        ),
        migrations.RemoveField(
            model_name='historicaltransaction',
            name='extract_run_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='extract_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='extract_run_id',
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='run',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.Run'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Run'),
        ),
    ]
