# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20171008_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrun',
            name='delimiter',
            field=models.CharField(default=',', max_length=20),
        ),
        migrations.AddField(
            model_name='run',
            name='delimiter',
            field=models.CharField(default=',', max_length=20),
        ),
    ]
