# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20171008_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrun',
            name='fields_description',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='historicalrun',
            name='fields_incoming',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='historicalrun',
            name='fields_incoming_sign',
            field=models.CharField(default='+', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalrun',
            name='fields_outgoing',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='historicalrun',
            name='fields_outgoing_sign',
            field=models.CharField(default='+', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalrun',
            name='fields_payment_date',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='run',
            name='fields_description',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='run',
            name='fields_incoming',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='run',
            name='fields_incoming_sign',
            field=models.CharField(default='+', max_length=1),
        ),
        migrations.AddField(
            model_name='run',
            name='fields_outgoing',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='run',
            name='fields_outgoing_sign',
            field=models.CharField(default='+', max_length=1),
        ),
        migrations.AddField(
            model_name='run',
            name='fields_payment_date',
            field=models.IntegerField(default=-1),
        ),
    ]
