# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20171010_0648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Run',
            new_name='Extract',
        ),
        migrations.RenameModel(
            old_name='HistoricalRun',
            new_name='HistoricalExtract',
        ),
        migrations.AlterModelOptions(
            name='historicalextract',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical extract'},
        ),
    ]
