# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='annual_dom',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='annual_frequency',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='annual_moy',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='monthly_dom',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='monthly_dow',
            field=models.CharField(default=b'MO', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='monthly_frequency',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='monthly_wom',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='occurrences',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='weekly_dow_fri',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='weekly_dow_mon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='weekly_dow_sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='weekly_dow_sun',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='weekly_dow_thu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='weekly_dow_tue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='weekly_dow_wed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='weekly_frequency',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
