# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20160410_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='monthly_dow',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
