# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20160613_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budget.Category'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='payment_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budget.PaymentType'),
        ),
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Category'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.PaymentType'),
        ),
    ]
