# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0010_auto_20160624_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaymentScheduleExclusions',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('exclusion_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical payment schedule exclusions',
            },
        ),
        migrations.CreateModel(
            name='PaymentScheduleExclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusion_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='historicalpaymentschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Last Payment Date'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Last Payment Date'),
        ),
        migrations.AddField(
            model_name='paymentscheduleexclusions',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.PaymentSchedule'),
        ),
        migrations.AddField(
            model_name='historicalpaymentscheduleexclusions',
            name='schedule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budget.PaymentSchedule'),
        ),
    ]
