# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20160703_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymentscheduleexclusions',
            name='exclusion_date',
        ),
        migrations.RemoveField(
            model_name='historicalpaymentscheduleexclusions',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='paymentscheduleexclusions',
            name='exclusion_date',
        ),
        migrations.RemoveField(
            model_name='paymentscheduleexclusions',
            name='schedule',
        ),
        migrations.AddField(
            model_name='historicalpaymentscheduleexclusions',
            name='exclusion_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budget.Payment'),
        ),
        migrations.AddField(
            model_name='historicalpaymentscheduleexclusions',
            name='main_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budget.Payment'),
        ),
        migrations.AddField(
            model_name='paymentscheduleexclusions',
            name='exclusion_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_payments', to='budget.Payment'),
        ),
        migrations.AddField(
            model_name='paymentscheduleexclusions',
            name='main_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='budget.Payment'),
        ),
    ]
