# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_auto_20160709_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscheduleexclusions',
            name='exclusion_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_payment', to='budget.Payment'),
        ),
        migrations.AlterField(
            model_name='paymentscheduleexclusions',
            name='main_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusion', to='budget.Payment'),
        ),
    ]
