# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_auto_20160709_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentscheduleexclusion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalpaymenttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalsubcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentscheduleexclusion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentschedulefrequency',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
