# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_auto_20170610_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budget.BankAccount'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='parent_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budget.HistoricalPayment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.BankAccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='parent_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Payment'),
        ),
    ]
