# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_auto_20170610_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.BankAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='parent_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.PaymentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.PaymentSchedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.SubCategory'),
        ),
    ]
