# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_historicallinkedpayment_linkedpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallinkedpayment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallinkedpayment',
            name='linked_payment',
        ),
        migrations.RemoveField(
            model_name='historicallinkedpayment',
            name='main_payment',
        ),
        migrations.RemoveField(
            model_name='historicallinkedpayment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='linkedpayment',
            name='linked_payment',
        ),
        migrations.RemoveField(
            model_name='linkedpayment',
            name='main_payment',
        ),
        migrations.RemoveField(
            model_name='linkedpayment',
            name='owner',
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Last Payment Date'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='occurrences',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='offset',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='offset_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Last Payment Date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='occurrences',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='offset',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='offset_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='parent_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget.Payment'),
        ),
        migrations.DeleteModel(
            name='HistoricalLinkedPayment',
        ),
        migrations.DeleteModel(
            name='LinkedPayment',
        ),
    ]
