# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0024_auto_20170725_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpayment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='occurrences',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='occurrences',
        ),
    ]
