# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_auto_20170725_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='offset',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='offset',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
