# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0028_auto_20170917_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Category'),
        ),
    ]
